[WIP] Set resource limits and requests for ocs and rook ceph operator
openshift/ocs-osd-deployer pull request #52
Opened 2021-05-21 12:04 UTC by kesavanvt

The OCS CSV is patched to set resource limits and requests

Signed-off-by: kesavan <kvellalo@redhat.com>

2021-05-26 12:10 UTC, nb-ohad requested changes

2021-05-26 12:10 UTC, nb-ohad commented on controllers/suite_test.go
> +	ocsCSV.Spec.InstallStrategy.StrategySpec.DeploymentSpecs = []opv1a1.StrategyDeploymentSpec{
Move the mock data into a separate func, as having it here just inflate the current flow without a reason
ocsCSV.Spec.InstallStrategy.StrategySpec.DeploymentSpecs = getMockOCSCSVDeploymentSpec()

2021-05-26 12:10 UTC, nb-ohad commented on controllers/managedocs_controller_test.go
> +							Expect(container.Resources).Should(Equal(ctrlutils.GetResourceRequirements("ocs-metrics-exporter")))
```suggestion
if (container.name == 'ocs-operator' ||
    container.name == 'rook-ceph-operator' ||
    container.name == 'ocs-metrics-exporter') {

    Expect(container.Resources).Should(Equal(ctrlutils.GetResourceRequirements(container.name)))
    
}
```

2021-05-26 12:10 UTC, nb-ohad commented on controllers/managedocs_controller_test.go
> +						case "ocs-operator":
If you are testing for a single value use `if` instead of `switch`

2021-05-26 12:10 UTC, nb-ohad commented on controllers/managedocs_controller_test.go
> +							}, timeout, interval).Should(Equal(ctrlutils.GetResourceRequirements("ocs-operator")))
Move the expected test outside of your mutation code. (outside the loop), the code structure should be:

1. prepare - loading the CSV
2. create test condition - the loop that finds the container and mutates it
3. wait for the result and assert - the `Eventually`

2021-05-27 15:57 UTC, nb-ohad requested changes

2021-05-27 15:57 UTC, nb-ohad commented on utils/utils.go
> +}
The `utils.go` was intended for generic utils once specific to a single domain. 
Either move this func to the controller or generalize to 

```func SelectByPrefix(list []metav1.Object, name string) metav1.Object```

2021-05-27 17:34 UTC, kesavanvt commented on controllers/managedocs_controller.go
> +	csv := utils.GetCSVByPrefix(csvList, deployerCSVPrefix)
Yes, we are using it more than once so retaining this function

2021-05-31 12:48 UTC, nb-ohad approved these changes

2021-05-31 12:48 UTC, nb-ohad commented
@JohnStrunk Please merge

2021-05-31 12:49 UTC, merged